package main;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.EventHandler;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.input.MouseEvent;

/**
 * This class contains all the event handlers of the buttons on the winning
 * screen.
 * 
 * @author Clinton Cao, Michiel Doesburg, Matthijs Halvemaan, Dmitry Malarev,
 *         Sunwei Wang.
 *
 */
public class WinningScreenController {

  @FXML
  private ResourceBundle resources;

  @FXML
  private URL location;

  @FXML
  private Button MainScreenButton;

  @FXML
  private Button NGPButton;

  /**
   * Automatically generated by Scenebuilder.
   * 
   * @param event
   *          kind of event.
   */
  @FXML
  void MainScreenEvent(MouseEvent event) {

  }

  /**
   * Automatically generated by SceneBuilder.
   * 
   * @param event
   *          kind of event.
   */
  @FXML
  void NGPEvent(MouseEvent event) {

  }

  /**
   * Initialize the button and set up the event handlers for the button.
   */
  @FXML
  void initialize() {
    assert MainScreenButton != null : "fx:id=\"MainScreenButton\" was not injected: "
        + "check your FXML file 'Untitled'.";
    assert NGPButton != null : "fx:id=\"MainScreenButton\" was not injected: "
        + "check your FXML file 'Untitled'.";

    MainScreenButton.setOnMouseClicked(new EventHandler<MouseEvent>() {

      @Override
      public void handle(MouseEvent event) {
        Game.setNewGamePlusMode(false);
        Game.switchScreen("FXML/MainScreen.fxml");
        if (Game.getMusicOn()) {
          Game.getMediaPlayer().play();
        }
        Game.getLogger().logSwitchScreen("MainScreen");

      }
    });

    NGPButton.setOnMouseClicked(new EventHandler<MouseEvent>() {

      @Override
      public void handle(MouseEvent event) {
        Game.setNewGamePlusMode(true);
        int score = MainScreenController.getPlayerFish().getScore();
        MainScreenController.setCurrScore(score);
        if (Game.getMusicOn()) {
          Game.getMediaPlayer().play();
        }
        Game.switchScreen("FXML/MainScreen.fxml");

      }
    });
  }
}