package main;

import javafx.event.EventHandler;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.input.MouseEvent;

import java.net.URL;
import java.util.ResourceBundle;

/**
 * This class contains all the event handlers of the buttons on the winning
 * screen.
 * 
 * @author Group 6
 *
 */
public class WinningScreenController {

  @FXML
  private ResourceBundle resources;

  @FXML
  private URL location;

  @FXML
  private Button MainScreenButton;

  /**
   * Automatically generated by Scenebuilder.
   * 
   * @param event
   *          kind of event.
   */
  @FXML
  void MainScreenEvent(MouseEvent event) {

  }

  /**
   * Initialize the button and set up the event handlers for the button.
   */
  @FXML
  void initialize() {
    assert MainScreenButton != null : "fx:id=\"MainScreenButton\" was not injected: "
        + "check your FXML file 'Untitled'.";

    MainScreenButton.setOnMouseClicked(new EventHandler<MouseEvent>() {

      @Override
      public void handle(MouseEvent event) {

        Game.switchScreen("FXML/MainScreen.fxml");

      }
    });
  }
}